const email_domain_list = [
    '@gmail.com',
    '@yahoo.com',
    '@aol.com',
    '@hotmail.com',
];

const name_list = [
    'Emma',
    'Liam',
    'Olivia',
    'Noah',
    'Ava',
    'Logan',
    'Sophia',
    'Lucas',
    'Isabella',
    'Mason',
    'Mia',
    'Ethan',
    'Amelia',
    'Oliver',
    'Charlotte',
    'Elijah',
    'Harper',
    'Aiden',
    'Aria',
    'James',
    'Ella',
    'Benjamin',
    'Evelyn',
    'Sebastian',
    'Abigail',
    'Jackson',
    'Emily',
    'Alexander',
    'Avery',
    'Jacob',
    'Scarlett',
    'Carter',
    'Madison',
    'Michael',
    'Sofia',
    'Jayden',
    'Chloe',
    'Daniel',
    'Lily',
    'Luke',
    'Mila',
    'Matthew',
    'Layla',
    'William',
    'Riley',
    'Jack',
    'Ellie',
    'Grayson',
    'Zoey',
    'Wyatt',
    'Luna',
    'Gabriel',
    'Elizabeth',
    'Henry',
    'Grace',
    'Julian',
    'Victoria',
    'Levi',
    'Aubrey',
    'Owen',
    'Penelope',
    'Ryan',
    'Hannah',
    'Leo',
    'Nora',
    'Jaxon',
    'Camila',
    'Lincoln',
    'Addison',
    'Nathan',
    'Stella',
    'Samuel',
    'Bella',
    'Isaiah',
    'Natalie',
    'David',
    'Maya',
    'Adam',
    'Skylar',
    'Joseph',
    'Aurora',
    'Eli',
    'Lillian',
    'John',
    'Paisley',
    'Anthony',
    'Savannah',
    'Muhammad',
    'Brooklyn',
    'Isaac',
    'Hazel',
    'Caleb',
    'Lucy',
    'Dylan',
    'Audrey',
    'Josiah',
    'Aaliyah',
    'Hunter',
    'Zoe',
    'Joshua',
];


const city_list = [
    'Agoura Hills, Los Angeles, CA',
    'Alhambra, Los Angeles, CA',
    'Arcadia, Los Angeles, CA',
    'Artesia, Los Angeles, CA',
    'Avalon, Los Angeles, CA',
    'Azusa, Los Angeles, CA',
    'Baldwin Park, Los Angeles, CA',
    'Bell, Los Angeles, CA',
    'Bell Gardens, Los Angeles, CA',
    'Bellflower, Los Angeles, CA',
    'Beverly Hills, Los Angeles, CA',
    'Bradbury, Los Angeles, CA',
    'Burbank, Los Angeles, CA',
    'Calabasas, Los Angeles, CA',
    'Carson, Los Angeles, CA',
    'Cerritos, Los Angeles, CA',
    'Claremont, Los Angeles, CA',
    'Commerce, Los Angeles, CA',
    'Compton, Los Angeles, CA',
    'Covina, Los Angeles, CA',
    'Cudahy, Los Angeles, CA',
    'Culver City, Los Angeles, CA',
    'Diamond Bar, Los Angeles, CA',
    'Downey, Los Angeles, CA',
    'Duarte, Los Angeles, CA',
    'El Monte, Los Angeles, CA',
    'El Segundo, Los Angeles, CA',
    'Gardena, Los Angeles, CA',
    'Glendale, Los Angeles, CA',
    'Glendora, Los Angeles, CA',
    'Hawaiian Gardens, Los Angeles, CA',
    'Hawthorne, Los Angeles, CA',
    'Hermosa Beach, Los Angeles, CA',
    'Hidden Hills, Los Angeles, CA',
    'Huntington Park, Los Angeles, CA',
    'Industry, Los Angeles, CA',
    'Inglewood, Los Angeles, CA',
    'Irwindale, Los Angeles, CA',
    'La Cañada Flintridge, Los Angeles, CA',
    'La Habra Heights, Los Angeles, CA',
    'La Mirada, Los Angeles, CA',
    'La Puente, Los Angeles, CA',
    'La Verne, Los Angeles, CA',
    'Lakewood, Los Angeles, CA',
    'Lancaster, Los Angeles, CA',
    'Lawndale, Los Angeles, CA',
    'Lomita, Los Angeles, CA',
    'Long Beach, Los Angeles, CA',
    'County seat, Los Angeles, CA',
    'Lynwood, Los Angeles, CA',
    'Malibu, Los Angeles, CA',
    'Manhattan Beach, Los Angeles, CA',
    'Maywood, Los Angeles, CA',
    'Monrovia, Los Angeles, CA',
    'Montebello, Los Angeles, CA',
    'Monterey Park, Los Angeles, CA',
    'Norwalk, Los Angeles, CA',
    'Palmdale, Los Angeles, CA',
    'Palos Verdes Estates, Los Angeles, CA',
    'Paramount, Los Angeles, CA',
    'Pasadena, Los Angeles, CA',
    'Pico Rivera, Los Angeles, CA',
    'Pomona, Los Angeles, CA',
    'Rancho Palos Verdes, Los Angeles, CA',
    'Redondo Beach, Los Angeles, CA',
    'Rolling Hills, Los Angeles, CA',
    'Rolling Hills Estates, Los Angeles, CA',
    'Rosemead, Los Angeles, CA',
    'San Dimas, Los Angeles, CA',
    'San Fernando, Los Angeles, CA',
    'San Gabriel, Los Angeles, CA',
    'San Marino, Los Angeles, CA',
    'Santa Clarita, Los Angeles, CA',
    'Santa Fe Springs, Los Angeles, CA',
    'Santa Monica, Los Angeles, CA',
    'Sierra Madre, Los Angeles, CA',
    'Signal Hill, Los Angeles, CA',
    'South El Monte, Los Angeles, CA',
    'South Gate, Los Angeles, CA',
    'South Pasadena, Los Angeles, CA',
    'Temple City, Los Angeles, CA',
    'Torrance, Los Angeles, CA',
    'Vernon, Los Angeles, CA',
    'Walnut, Los Angeles, CA',
    'West Covina, Los Angeles, CA',
    'West Hollywood, Los Angeles, CA',
    'Westlake Village, Los Angeles, CA',
    'Whittier, Los Angeles,, CA',
    'Atherton, San Mateo, CA',
    'Belmont, San Mateo, CA',
    'Brisbane, San Mateo, CA',
    'Burlingame, San Mateo, CA',
    'Colma, San Mateo, CA',
    'Daly City, San Mateo, CA',
    'East Palo Alto, San Mateo, CA',
    'Foster City, San Mateo, CA',
    'Half Moon Bay, San Mateo, CA',
    'Hillsborough, San Mateo, CA',
    'Menlo Park, San Mateo, CA',
    'Millbrae, San Mateo, CA',
    'Pacifica, San Mateo, CA',
    'Portola Valley, San Mateo, CA',
    'Redwood CityCounty seat, San Mateo, CA',
    'San Bruno, San Mateo, CA',
    'San Carlos, San Mateo, CA',
    'South San Francisco, San Mateo, CA',
    'Woodside, San Mateo, CA',
]


module.exports = {
    email_domain_list,
    name_list,
    city_list,
}
